name: Docker Build & Push 

on:
  push:
    branches:
      - feature-*

  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter Tag for Docker Image to be built'     
        required: true
        default: 'latest'
  
env:
  DOCKER_REPO: repo1
  APP_NAME: app1
  tag: x1
  
jobs:
  docker_build:
    name: Docker Build & Push 
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the Branch
        uses: actions/checkout@v2

      - name: Docker Login to Jfrog Artifactory
        run: |
          docker login -u "${{ secrets.USERNAME }}" -p "${{ secrets.PASSWORD }}" artifactory.jfrog.io
        
      - name: Docker Build, Tag & Push to JFrog Artifactory  
        run: |
         docker build --no-cache -f ./Dockerfile -t artifactory.jfrog.io/${{ env.DOCKER_REPO }}/${{ env.APP_NAME }}:${{ github.event.inputs.tag }} .
         docker push artifactory.jfrog.io/${{ env.DOCKER_REPO }}/${{ env.APP_NAME }}:${{ github.event.inputs.tag }}
