# name: Scheduled GitHub Action

# on:
#   schedule:
#     - cron: '*/15 * * * *'  # Runs at every 15th min
  
  
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:

#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Print Message
#         run: |
#           echo "Hello World from scheduled GitHub Actions" 


name: Fetching the first commit on the branch 

on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch First Commit 
        run: |
          echo "Printing command output"
          git rev-list --max-parents=0 HEAD
          COMMIT=$(git rev-list --max-parents=0 HEAD)
          echo "Printing COMMIT"
          echo $COMMIT
          echo "FIRST_COMMIT=$COMMIT" >> GITHUB_ENV
          echo "Printing the First Commit..."
          echo ${{ env.FIRST_COMMIT  }}
         
        
      
