# name: Scheduled GitHub Action

# on:
#   schedule:
#     - cron: '*/15 * * * *'  # Runs at every 15th min
  
  
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:

#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Print Message
#         run: |
#           echo "Hello World from scheduled GitHub Actions" 


name: Fetching the first commit on the branch 

on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get First Commit 
        run: |
            echo "FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_ENV

      - name: Print First Commit 
        run: |
            echo "${{ env.FIRST_COMMIT }}"

  build2:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Print First Commit from Previous Job
        run: |
            echo "${{ needs.build.env.FIRST_COMMIT }}"          

      
          
         
        
      
