name: Workflow 1
on:
  push:
    branches: main
  
jobs:
  build1:
    runs-on: ubuntu-latest
    outputs: 
      FIRST_COMMIT: ${{ steps.set_first_commit.outputs.FIRST_COMMIT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get First Commit 
        id: set_first_commit
        run: |
            echo "FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_OUTPUT

      - name: Print First Commit 
        run: |
            echo "${{ env.FIRST_COMMIT }}"

  build2:
    runs-on: ubuntu-latest
    needs: build1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print First Commit from Previous Job
        run: |
            echo "${{ needs.build1.outputs.FIRST_COMMIT }}"  

  build3:
    needs: build1
    uses: ./.github/workflows/ci2.yml
    with: 
        commit_id: ${{ needs.build1.outputs.FIRST_COMMIT }}

      
          
         
        
      
