name: Workflow 2
on:
  workflow_dispatch:
    inputs:
      commit_id:
       type: string
       description: 'First Commit from Workflow1'

jobs:
  build4:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print received commit_id from Workflow 1
        run: |
            echo ${{ github.event.inputs.commit_id }}
     