name: Multiple Event Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      push_image:
        description: 'push image'  
        default: 'true'   
        required: true

      first_release:
        description: 'first release'  
        default: 'false'   
        required: true
        
      previous_release_tag:
        description: 'first release' 
        default: 'test'    
        required: true

  release:
    types: [published] 

env:
  push_image: ${{ github.event_name == 'release' && 'true' || inputs.push_image }}
  first_release: ${{ github.event_name == 'release' && 'false' || inputs.first_release }}
  previous_release_tag: ${{ github.event_name == 'release' && github.ref_name || inputs.previous_release_tag }}


        
  
jobs:
  build1:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    outputs: 
      base_tag: ${{ steps.set_base_tag.outputs.base_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set base_tag
        id: set_base_tag
        if: github.event.inputs.push_image == ''    # <= Condition for testing workflow 
        #if: github.event.inputs.push_image != '' || github.event.inputs.push_image == 'true'  # <= Actual condition
        run: |
            echo "Input PI:${{ inputs.push_image}}"
            echo "ENV PI:${{ env.push_image}}"
            echo "Input FR:${{ inputs.first_release}}"
            echo "ENV FR:${{ env.first_release}}"
            echo "Input PR:${{ inputs.previous_release_tag}}"
            echo "Env PR:${{ env.previous_release_tag}}"
            if ${{ env.first_release}} == "true"
            then 
              echo "base_tag=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_OUTPUT
            else
              echo "base_tag=${{ env.previous_release_tag }}" >> $GITHUB_OUTPUT
            fi


  build2:
    runs-on: ubuntu-latest
    needs: build1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print First Commit from Previous Job (Depends on Build1)
        run: |
            echo "${{ needs.build1.outputs.base_tag }}"  

  build3:
    runs-on: ubuntu-latest
    needs: build2
    # uses: ./.github/workflows/ci2.yml
    # with: 
    #     commit_id: ${{ needs.build1.outputs.base_tag}}    
     steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print First Commit from Previous Job ( Depends on Build2)
        run: |
            echo "${{ needs.build1.outputs.base_tag }}"        

  
