name: Workflow 3
on:
  workflow_dispatch:
    inputs:
      first_release:
        description: 'first release'  
        default: 'false'   
        required: true
        
       

      previous_release_tag:
        type: string
        description: 'first release' 
        default: 'test'    
        required: true
        
        
  
jobs:
  build1:
    runs-on: ubuntu-latest
    outputs: 
      base_tag: ${{ steps.set_first_commit.outputs.base_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get First Commit 
        id: base_tag
        run: |
            echo "FR:${{ github.event.inputs.first_release}}"
            echo "PR:${{ github.event.inputs.previous_release_tag}}"
            if ${{ github.event.inputs.first_release}} == "true"
            then 
              echo "base_tag=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_OUTPUT
            else
              echo "base_tag=${{ github.event.inputs.previous_release_tag}}" >> $GITHUB_OUTPUT
            fi


  build2:
    runs-on: ubuntu-latest
    needs: build1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print First Commit from Previous Job
        run: |
            echo "${{ needs.build1.outputs.base_tag }}"  

  