name: Workflow 3
on:
  workflow_dispatch:
    inputs:
      push_image:
        description: 'push image'  
        default: 'true'   
        required: true

      first_release:
        description: 'first release'  
        default: 'false'   
        required: true
        
      previous_release_tag:
        description: 'first release' 
        default: 'test'    
        required: true

  release:
    types: [published]      
        
  
jobs:
  build1:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    outputs: 
      base_tag: ${{ steps.set_base_tag.outputs.base_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get First Commit 
        id: set_base_tag
        if: github.event.inputs.push_image == 'true' #&& github.event.inputs.push_image != ''
        run: |
            echo "PI:${{ inputs.push_image}}"
            echo "FR:${{ inputs.first_release}}"
            echo "PR:${{ inputs.previous_release_tag}}"
            if ${{ inputs.first_release}} == "true"
            then 
              echo "base_tag=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_OUTPUT
            else
              echo "base_tag=${{ inputs.previous_release_tag }}" >> $GITHUB_OUTPUT
            fi


  build2:
    runs-on: ubuntu-latest
    needs: build1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print First Commit from Previous Job
        run: |
            echo "${{ needs.build1.outputs.base_tag }}"  

  