name: Workflow 3
on:
  push:
    branches: main

  # Uncomment below for scheduled workflow
  # schedule:
  #   - cron: '*/15 * * * *'  # Runs at every 15th min
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Message
        run: |
          echo "Hello World from scheduled GitHub Actions" 