name: Workflow 4
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'  
        type: choice
        default: "dev"  
        required: true
        options:
            - "dev"
            - "uat"
            - "prd"

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup & Validate Environment Variables for DEV/UAT/PRD
        env:
          DEV_PROJECT: ${{ secrets.DEV }}
          UAT_PROJECT: ${{ secrets.UAT }}
          PRD_PROJECT: ${{ secrets.PRD }}
        run: |
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            echo "PROJECT=$DEV_PROJECT" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" = "uat" ]; then
             echo "PROJECT=$DEV_PROJECT" >> $GITHUB_ENV
             echo "UAT Environment" 
          elif [ "${{ github.event.inputs.environment }}" = "prd" ]; then
            echo "PROJECT=$DEV_PROJECT" >> $GITHUB_ENV
            echo "PRD Environment"  
          else
            echo "Invalid Input Environment. No Environment Variables Set"  
          fi
          echo ${DEV_PROJECT}
          echo ${{ secrets.DEV }}
          
          
           
         

              


  