name: Workflow to clone other repo 
on:
  push:
    branches: main

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone other repo
        uses: actions/checkout@v3
        with:
          repository: anuragsingh2207/github-actions-2
          ref: main
          path: github-actions-2

      - name: Validate clone and Fetch Commit Details
        run: |
            cd github-actions-2
            echo "Clone Successful.."
            pwd
            ls -alrtgh
            echo "Fetch Commit Details..."
            echo "BRANCH_CLONED=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
            echo "Print output of git log -1"
            git log -1
            echo "LAST_COMMIT=$(git log --pretty=format:'Name:%an, Message: %s, Date: %ad' -1)" >> $GITHUB_ENV
            echo "LAST_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
         

      - name: Generate Summary Post Clone
        run: |
          echo "Clone Successful..." >> $GITHUB_STEP_SUMMARY
          echo "Branch Cloned: ${{ env.BRANCH_CLONED }}" >> $GITHUB_STEP_SUMMARY
          echo "Last Commit: ${{ env.LAST_COMMIT }}" >> $GITHUB_STEP_SUMMARY
          echo "Last Commit SHA: ${{ env.LAST_COMMIT_SHA }}" >> $GITHUB_STEP_SUMMARY


      

      
          
         
        
      
