name: Workflow to clone other repo 
on:
  push:
    branches: main

jobs:
  clone-repo:
    name: Clone Repo
    runs-on: ubuntu-latest
    steps:
      - name: Clone other repo
        uses: actions/checkout@v3
        with:
          repository: anuragsingh2207/github-actions-2
          ref: main
          path: github-actions-2

      - name: Validate clone and Fetch Commit Details
        run: |
            echo "Current working directory:"
            pwd 
            echo "Listing Files..."
            ls -al
            echo "Change to cloned directory:"
            cd github-actions-2
            echo "BRANCH_CLONED=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
            echo "LAST_COMMIT=$(git log --pretty=format:'Committer Name:%an, Commit Message: %s, Commit Date: %ad' -1)" >> $GITHUB_ENV
            echo "LAST_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      
      - name: Validate and Set Path
        run: |
            echo "Current working directory:"
            pwd
            echo "Listing Files..."
            ls -al
            echo "Listing Files recursively..."
            ls -alR
            ls -alR /home/runner/work/github-actions/github-actions/

      - name: Run cloned worflow
        uses: ./github-actions-2/.github/workflows/actions
        with: 
         message: 'Hello World!!!'      
      
      - name: Generate Summary Post Clone
        run: |
          echo "Branch Cloned: ${{ env.BRANCH_CLONED }}" >> $GITHUB_STEP_SUMMARY
          echo "Last Commit Details: ${{ env.LAST_COMMIT }}" >> $GITHUB_STEP_SUMMARY
          echo "Last Commit SHA: ${{ env.LAST_COMMIT_SHA }}" >> $GITHUB_STEP_SUMMARY
          echo "Last Commit SHA URL: (https://github.com/anuragsingh2207/github-actions-2/commit/${{ env.LAST_COMMIT_SHA }})" >> $GITHUB_STEP_SUMMARY



    
      
          
         
        
      
