name: Workflow to clone other repo 
on:
  push:
    branches: main

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone other repo
        uses: actions/checkout@v3
        with:
          repository: anuragsingh2207/github-actions-2
          ref: main
          path: github-actions-2

      - name: Validate clone and Fetch First Commit
        run: |
            echo $GITHUB_WORKSPACE
            cd github-actions-2
            pwd
            ls -alrtgh
            echo "Setting First Commit..."
            echo "FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_ENV
         

      - name: Generate Summary Post Clone
        run: |
          echo "Clone Successful" >> $GITHUB_STEP_SUMMARY
          echo "First Commit: ${{ env.FIRST_COMMIT }}" >> $GITHUB_STEP_SUMMARY

      

      
          
         
        
      
