name: Dispatcher 1
on:
  workflow_dispatch:
    inputs:
      build_deploy:
        type: choice
        description: 'Deploy (true/false)'  
        default: true   
        required: true
        options:
          - true
          - false
      tag:
        description: 'Docker Image Tag'  
        default: 'v1.0.1'   
        required: true

jobs:
  dispatch:
    name: Dispatch1
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatcher1 to Receiver1
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            --request POST \
            --data '{
              "event_type": "build-dispatch-1",
              "client_payload": {
                "foo": "bar",
                "tag": "${{ github.event.inputs.tag }}"
                "deploy": "'${{ github.event.inputs.build_deploy }}'"
              }
            }' \
            https://api.github.com/repos/anuragsingh2207/github-actions-2/dispatches

