name: Dispatcher
on:
  push:
    branches: [main]

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # - name: Dispatch to workflows
      #   run: |
      #       curl -H "Accept: application/vnd.github.everest-preview+json" \
      #       -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
      #       --request POST \
      #       --data '{
      #         "event_type": "build-dispatch",
      #         "client_payload": {
      #           "foo": "bar",
      #           "ref": "develop"
      #         }
      #       }' \
      #       https://api.github.com/repos/anuragsingh2207/github-actions-2/dispatches

        - name: Dispatch to workflows
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.DISPATCH_TOKEN }}
            script: |
              await github.rest.actions.createWorkflowDispatch({
              owner: 'anuragsingh2207/',
              repo: 'github-actions-2',
              workflow_id: 'receiver.yml',
              ref: 'develop'
              })

