name: Dispatcher
on:
  push:
    branches: [main]

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            --request POST \
            --data '{
              "event_type": "build-dispatch",
              "client_payload": {
                "foo": "bar",
                "branch": "develop"  
              }
            }' \
            https://api.github.com/repos/anuragsingh2207/github-actions-2/dispatches
