name: Python with GitHub Actions
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'  
        type: choice
        default: "dev"  
        required: true
        options:
            - "dev"
            - "uat"
            - "prd"

      msg:
        description: 'Message'  
        type: string
        default: "hello"  
        required: true

      msg1:
        description: 'Message1'  
        default: "world"  
        required: true

      tag:
        description: 'Docker Tag'  
        default: "1.2.3"  
        required: true

      release:
        description: 'Release Tag'  
        default: "v1.2.3"  
        type: string
        required: true
        

env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Run Python Script
        run: python main.py