name: Python with GitHub Actions
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'  
        type: choice
        default: "dev"  
        required: true
        options:
            - "dev"
            - "uat"
            - "prd"

env:
      ENVIORNMENT: ${{ github.event.input.environment }}

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
          with:
            python-version: '3.10' 

      - name: Run Python Script
        run: python main.py