# name: Scheduled GitHub Action

# on:
#   schedule:
#     - cron: '*/15 * * * *'  # Runs at every 15th min
  
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:

#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Print Message
#         run: |
#           echo "Hello World from scheduled GitHub Actions" 