name: Validate S3cr3tz Workflow
on: [push]

jobs:
  debug:
    name: Show the secret
    runs-on: ubuntu-latest

    steps:

    - name: Show Secret Value
      run: |
        echo "${{ secrets.USERNAME }}" | sed 's/./& /g'
